# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Controller.Finder import load_list, save_list

TITLES_FILE = "Models/titles.txt"


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(644, 480)
        font = QtGui.QFont()
        font.setPointSize(14)
        Dialog.setFont(font)
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.tableWidget.setFont(font)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(1)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(300)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(100)
        self.gridLayout.addWidget(self.tableWidget, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnNewRow = QtWidgets.QPushButton(Dialog)
        self.btnNewRow.setObjectName("btnNewRow")
        self.verticalLayout.addWidget(self.btnNewRow)
        self.btnDeleteRow = QtWidgets.QPushButton(Dialog)
        self.btnDeleteRow.setObjectName("btnDeleteRow")
        self.verticalLayout.addWidget(self.btnDeleteRow)
        spacerItem = QtWidgets.QSpacerItem(20, 300, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(150, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.btnSave = QtWidgets.QPushButton(Dialog)
        self.btnSave.setMinimumSize(QtCore.QSize(150, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnSave.setFont(font)
        self.btnSave.setObjectName("btnSave")
        self.horizontalLayout.addWidget(self.btnSave)
        self.btnCancel = QtWidgets.QPushButton(Dialog)
        self.btnCancel.setMinimumSize(QtCore.QSize(150, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnCancel.setFont(font)
        self.btnCancel.setObjectName("btnCancel")
        self.horizontalLayout.addWidget(self.btnCancel)
        spacerItem2 = QtWidgets.QSpacerItem(150, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.gridLayout_2.addLayout(self.horizontalLayout, 1, 0, 1, 2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Titel bearbeiten"))
        self.tableWidget.setSortingEnabled(True)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Titel"))
        self.btnNewRow.setText(_translate("Dialog", "Neu"))
        self.btnDeleteRow.setText(_translate("Dialog", "Löschen"))
        self.btnSave.setText(_translate("Dialog", "Speichern"))
        self.btnCancel.setText(_translate("Dialog", "Abbrechen"))

    def load_data(self):
        titles = load_list(TITLES_FILE)
        self.tableWidget.setRowCount(len(titles))
        row = 0
        for title in titles:
            if title != "":
                self.tableWidget.setItem(row, 0, QtWidgets.QTableWidgetItem(title))
                row += 1
            else:
                self.tableWidget.removeRow(row)

    def save_data(self):
        new_titles = []
        rows = self.tableWidget.rowCount()
        for row in range(rows):
            try:
                new_titles.append(self.tableWidget.item(row, 0).text() + '\n')
            except:
                pass
        save_list(new_titles, TITLES_FILE)


    def insert_row(self):
        rows = self.tableWidget.rowCount()
        self.tableWidget.insertRow(rows)

    def remove_row(self):
        curr_row = self.tableWidget.currentRow()
        self.tableWidget.removeRow(curr_row)
