# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Dialog_Female_Salut.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_Female_Salut(object):
    def setupUi(self, Dialog_Female_Salut):
        Dialog_Female_Salut.setObjectName("Dialog_Female_Salut")
        Dialog_Female_Salut.resize(644, 480)
        font = QtGui.QFont()
        font.setPointSize(14)
        Dialog_Female_Salut.setFont(font)
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog_Female_Salut)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.tableWidget = QtWidgets.QTableWidget(Dialog_Female_Salut)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.tableWidget.setFont(font)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(1)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(300)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(100)
        self.gridLayout.addWidget(self.tableWidget, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnNewRow = QtWidgets.QPushButton(Dialog_Female_Salut)
        self.btnNewRow.setObjectName("btnNewRow")
        self.verticalLayout.addWidget(self.btnNewRow)
        self.btnDeleteRow = QtWidgets.QPushButton(Dialog_Female_Salut)
        self.btnDeleteRow.setObjectName("btnDeleteRow")
        self.verticalLayout.addWidget(self.btnDeleteRow)
        spacerItem = QtWidgets.QSpacerItem(20, 300, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(150, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.btnSave = QtWidgets.QPushButton(Dialog_Female_Salut)
        self.btnSave.setMinimumSize(QtCore.QSize(150, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnSave.setFont(font)
        self.btnSave.setObjectName("btnSave")
        self.horizontalLayout.addWidget(self.btnSave)
        self.btnCancel = QtWidgets.QPushButton(Dialog_Female_Salut)
        self.btnCancel.setMinimumSize(QtCore.QSize(150, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnCancel.setFont(font)
        self.btnCancel.setObjectName("btnCancel")
        self.horizontalLayout.addWidget(self.btnCancel)
        spacerItem2 = QtWidgets.QSpacerItem(150, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.gridLayout_2.addLayout(self.horizontalLayout, 1, 0, 1, 2)

        self.retranslateUi(Dialog_Female_Salut)
        QtCore.QMetaObject.connectSlotsByName(Dialog_Female_Salut)

    def retranslateUi(self, Dialog_Female_Salut):
        _translate = QtCore.QCoreApplication.translate
        Dialog_Female_Salut.setWindowTitle(_translate("Dialog_Female_Salut", "Weibliche Anreden bearbeiten"))
        self.tableWidget.setSortingEnabled(True)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog_Female_Salut", "Anrede"))
        self.btnNewRow.setText(_translate("Dialog_Female_Salut", "Neu"))
        self.btnDeleteRow.setText(_translate("Dialog_Female_Salut", "Löschen"))
        self.btnSave.setText(_translate("Dialog_Female_Salut", "Speichern"))
        self.btnCancel.setText(_translate("Dialog_Female_Salut", "Abbrechen"))
